name: 'Setup Java'
description: 'JAVA Setup for Otter Library'

inputs:
  install-jdk:
    description: 'Option to install java'
    required: false
    default: 'false'
  mvn-version:
    description: 'Mvn version to install'
    required: false
    default: '3.8.7'

runs:
  using: "composite"
  steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.mvn-version }}
    - name: Set up JDK 17
      uses: actions/setup-java@9704b39bf258b59bc04b50fa2dd55e9ed76b47a8 # v4.1.0
      if: inputs.install-jdk == 'true'
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
