name: Download Build Output
description: Download and restore the `dist` folders from github artifact (check ../upload-build-output)

runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      if: github.event_name != 'workflow_run'
      with:
        name: dist
        path: '.'

    - name: 'Download artifact'
      uses: actions/github-script@v6
      if: github.event_name == 'workflow_run'
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "dist"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
             owner: context.repo.owner,
             repo: context.repo.repo,
             artifact_id: matchArtifact.id,
             archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/dist.zip`, Buffer.from(download.data));

    - run: unzip -q -n dist.zip
      shell: bash
    - run: rm -f dist.zip
      shell: bash
