name: Main CI

concurrency:
  group: ci-${{ github.ref }}-main
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
  merge_group:
    types: [checks_requested]

env:
  NX_PARALLEL: ${{ vars.NX_PARALLEL }}
  NX_TASK_TARGET_CONFIGURATION: ci
  YARN_ENABLE_HARDENED_MODE: 0
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./tools/github-actions/setup
      - run: yarn build
      - run: yarn playwright install
      - name: Run e2e tests
        run: |
          npx --yes http-server apps/showcase/dist/browser -p 8080 -s &
          npx --yes wait-on $PLAYWRIGHT_TARGET_URL -t 5000
          yarn workspace @o3r/showcase run test:playwright:sanity -g "Visual comparison"
        shell: bash
        env:
          PLAYWRIGHT_TARGET_URL: http://127.0.0.1:8080
      - if: failure()
        run: |
          git checkout -b test/branche
          git add -A
          git -c user.name="test" -c user.email="test@test.test" commit -am "test: screenshots" -n
          git push origin test/branche
