name: Test publish

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false
        description: Token to use Nx Cloud token

jobs:
  test-publish:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        packageManager: [yarn]
    runs-on: ${{ matrix.os }}
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      ENFORCED_PACKAGE_MANAGER: ${{ matrix.packageManager }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./tools/github-actions/setup
      - name: Setup verdaccio once for all tests
        if: success() || failure()
        id: setup-verdaccio
        run: |
          npx --yes verdaccio --config $GITHUB_WORKSPACE\\.verdaccio\\conf\\config2.yaml --listen http://127.0.0.1:4873 &
          npx --yes wait-on http://127.0.0.1:4873 -t 180000
          yarn verdaccio:login
        shell: bash
        timeout-minutes: 10
